name: Android CI test
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "README.md"
      - "README_en.md"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20.x
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - run: chmod 777 ./gradlew

      - name: Build Docs
        run: ./gradlew app:buildDocs
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Build with Gradle
        run: | 
          ./gradlew autojs:buildJsModule
          ./gradlew :inrt:assemble
          ./gradlew :app:assembleRelease
      - uses: actions/upload-artifact@v4
        with:
          name: apks(no signing)
          path: app/build/outputs/apk/v7/release/*.apk
